export enum Permission {
  OBRA_CREATE = 'OBRA_CREATE',
  OBRA_UPDATE = 'OBRA_UPDATE',
  OBRA_VIEW = 'OBRA_VIEW',

  MEDICAO_CREATE = 'MEDICAO_CREATE',
  MEDICAO_APPROVE = 'MEDICAO_APPROVE',
  MEDICAO_VIEW = 'MEDICAO_VIEW',

  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_VIEW = 'USER_VIEW',

  CUSTO_LANCAR = 'CUSTO_LANCAR',
  PAGAMENTO_APROVAR = 'PAGAMENTO_APROVAR',
}
